/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.demo.tela;

import javax.swing.JFileChooser;
import javax.swing.JTextField;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

import org.apache.commons.io.FilenameUtils;




/**
 *
 * @author dev
 */
public class TelaPrincipal extends javax.swing.JFrame {
   

   // ConverteWordemPDF con = new ConverteWordemPDF();
    ConvertDoctoPDF pdf = new ConvertDoctoPDF();
    ConvertPDFtoDoc docx = new ConvertPDFtoDoc();
   
    
    public TelaPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
        botaoConverterDoctoPDF.setEnabled(false);
        botaoConverterPDFtoDoc.setEnabled(false);
       
    }
    
    public void selecionaCamino(JTextField field){
        
            JFileChooser file = new JFileChooser(); 
            //file.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY); 
            
            FileNameExtensionFilter filter = new FileNameExtensionFilter("Tipos: docx,doc,pdf","docx", "doc", "pdf"); //tipo de arquivo
            file.addChoosableFileFilter(filter);
            file.setFileSelectionMode(JFileChooser.FILES_ONLY);
            int i= file.showSaveDialog(null);
          if (i==1){
              String dir = System.getProperty("user.home");
              field.setText(field.getText());
          } else {
              File arquivo = file.getSelectedFile();
              field.setText(arquivo.getPath());
            // JtextFieldLocal.setText(arquivo.getPath()+".txt");
          }
    }
    
 
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jTextFieldArquivo = new javax.swing.JTextField();
        botaoDocx = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        botaoConverterDoctoPDF = new javax.swing.JButton();
        botaoConverterPDFtoDoc = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Conversor de Arquivos");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Selecione o tipo de Arquivo"));

        botaoDocx.setIcon(new javax.swing.ImageIcon(getClass().getResource("/documentos56.png"))); // NOI18N
        botaoDocx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoDocxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(botaoDocx)
                .addGap(8, 8, 8)
                .addComponent(jTextFieldArquivo, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(botaoDocx))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jTextFieldArquivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Converter"));

        botaoConverterDoctoPDF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/doctopdf250x92.png"))); // NOI18N
        botaoConverterDoctoPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoConverterDoctoPDFActionPerformed(evt);
            }
        });

        botaoConverterPDFtoDoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pdftodoc92.png"))); // NOI18N
        botaoConverterPDFtoDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoConverterPDFtoDocActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botaoConverterPDFtoDoc, javax.swing.GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE)
                    .addComponent(botaoConverterDoctoPDF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(8, 8, 8))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(botaoConverterPDFtoDoc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botaoConverterDoctoPDF)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoDocxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoDocxActionPerformed
        selecionaCamino(jTextFieldArquivo);
        String ext = FilenameUtils.getExtension(jTextFieldArquivo.getText());
        if ("docx".equalsIgnoreCase(ext)) {
            botaoConverterDoctoPDF.setEnabled(true);
         } else if ("pdf".equalsIgnoreCase(ext)) { 
            botaoConverterPDFtoDoc.setEnabled(true);
        }else{
           JOptionPane.showMessageDialog(null, "TIPO DE ARQUIVO INVÁLIDO. SOMENTE .PDF e .docx são permitidos.");
           jTextFieldArquivo.setText("");
         } 
        
        
    }//GEN-LAST:event_botaoDocxActionPerformed

    private void botaoConverterDoctoPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoConverterDoctoPDFActionPerformed
      pdf.convertDocInPDF(jTextFieldArquivo.getText());
    // D4j.Convert(jTextFieldArquivo.getText());
      jTextFieldArquivo.setText("");
       botaoConverterDoctoPDF.setEnabled(false);
       botaoConverterPDFtoDoc.setEnabled(false);
      
    }//GEN-LAST:event_botaoConverterDoctoPDFActionPerformed

    private void botaoConverterPDFtoDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoConverterPDFtoDocActionPerformed
        try {
            docx.convertPdftoDoc(jTextFieldArquivo.getText());
            jTextFieldArquivo.setText("");
            botaoConverterDoctoPDF.setEnabled(false);
            botaoConverterPDFtoDoc.setEnabled(false);
        } catch (IOException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }//GEN-LAST:event_botaoConverterPDFtoDocActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoConverterDoctoPDF;
    private javax.swing.JButton botaoConverterPDFtoDoc;
    private javax.swing.JButton botaoDocx;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextFieldArquivo;
    // End of variables declaration//GEN-END:variables
}
